spring:
  application:
    name: dorm-repair-backend
  profiles:
    active: dev

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
